version: '3.4'

services:

  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'SqlServerDb'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "Numsey#2023"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'
    expose:
      - 1433 

  efcoresqlserver:
    container_name: ProductsWebApiContainer
    image: ${DOCKER_REGISTRY-}productswebapi
    build:
      context: .
      dockerfile: EFCoreSQLServer/Dockerfile
    depends_on:
      - SqlServerDb

