version: '3.4'

services:
  efcoresqlserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32033:80" 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro