@rootUrl=http://localhost:32033/api/Products

### Get all products
GET {{rootUrl}}
###Authorization: Bearer {{token}}
###

### Get product by ID (Needs to replace the id)
GET {{rootUrl}}/1651317556

###

### Create a new product
POST {{rootUrl}}
Content-Type: application/json

{
  "Name": "New Product",
  "Price": 19.99,
  "Description": "This is a new product."
}

###

### Update a product  (Needs to replace the id)
PUT {{rootUrl}}/1651317556
Content-Type: application/json

{
  "Name": "Updated Product",
  "Price": 24.99,
  "Description": "This product has been updated."
}

###

### Delete a product  (Needs to replace the id)
DELETE {{rootUrl}}/-436503997
